## Tensorflow basics


In [1]:
import tensorflow as tf
print(tf.__version__)

1.9.0


In [2]:
hello = tf.constant('hello')
world = tf.constant('world')
print(type(hello))
print(hello)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("Const:0", shape=(), dtype=string)


##Block that will run tensorflow session

In [3]:
with tf.Session() as sess:
    result = sess.run(hello+world)
print(result)

b'helloworld'


In [4]:
a = tf.constant(10)
b = tf.constant(20)
print(type(a))
print(a+b)

<class 'tensorflow.python.framework.ops.Tensor'>
Tensor("add_1:0", shape=(), dtype=int32)


In [5]:
a+b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [6]:
a+b

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [7]:
a+b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [8]:
with tf.Session() as sess:
    result = sess.run(a+b)
print(result)

30


In [0]:
const = tf.constant(10)
fill_mat = tf.fill((4, 4), 10)
myzeros = tf.zeros((4, 4))
myones = tf.ones((4, 4))
myrandom = tf.random_normal((4, 4), mean=0, stddev=1.0)
myrand = tf.random_uniform((4,4), minval=0, maxval=1)

In [10]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [0]:
mylist = [const, fill_mat, myzeros, myones, myrandom, myrand]
sess = tf.InteractiveSession()#used only for notebooks else use only with tf.Session as sess:

In [12]:
for element in mylist:
    print(sess.run(element),'\n')#Alternatively we can use element.eval() instead of sess.run(element)

10 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[-0.3121867  -0.5486291   0.43276173  0.35691783]
 [ 0.40759742 -0.2680981  -0.41499448 -0.22577967]
 [-0.9951731   0.05632048  1.3289064   0.28551292]
 [ 0.27563736  0.86364555 -2.0367527  -1.5522063 ]] 

[[0.33895338 0.73612523 0.7233604  0.10672295]
 [0.64512706 0.11649704 0.31120098 0.09589684]
 [0.2717526  0.45117807 0.24153543 0.19222462]
 [0.34387064 0.46703112 0.7273501  0.63105106]] 



In [13]:
a = tf.constant([[1,2],
                 [3,4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [14]:
b = tf.constant([[10],
                 [100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [15]:
result = tf.matmul(a,b)
result

<tf.Tensor 'MatMul:0' shape=(2, 1) dtype=int32>

In [16]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [17]:
result.eval()

array([[210],
       [430]], dtype=int32)

##Tensorflow Graphs

In [0]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2

In [0]:
with tf.Session() as sess:
    result = sess.run(n3)

In [20]:
print(result)
print(n3)

3
Tensor("add_6:0", shape=(), dtype=int32)


In [21]:
print(tf.get_default_graph())

In [22]:
g = tf.Graph()
print(g)

In [23]:
graph_one = tf.get_default_graph()
print(graph_one)#Both default graph have same memory location

In [24]:
graph_two = tf.Graph()
print(graph_two)

In [25]:
#let's make graph_two as default graph
with graph_two.as_default():
    print(graph_two is tf.get_default_graph())#inside gives True
print(graph_two is tf.get_default_graph())#outside gives False coz outside the block graph_one is default graph

True
False


Variables and placeholders
Variables can hold values of weights and biases throughout the session. Varibles need to be initialized. Placeholders are initially empty and are used to feed in the actual training examples.(usually in small batches). However they do need to be declared expected data type(tf.float32) with an optional shape argument.

In [0]:
sess = tf.InteractiveSession()# so that we can run the sessions in multiple cells 

In [27]:
my_tensor = tf.random_uniform((4,4),0,1)
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [31]:
my_var = tf.Variable(initial_value=my_tensor)
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [35]:
init = tf.global_variables_initializer() #initializing the tf variables
sess.run(init)
sess.run(my_var)

array([[0.35143209, 0.88159406, 0.09357893, 0.11790812],
       [0.6620132 , 0.47957265, 0.56097984, 0.14640677],
       [0.24625683, 0.46647406, 0.7148727 , 0.10647583],
       [0.3109945 , 0.16820872, 0.16695929, 0.18667829]], dtype=float32)

In [0]:
ph = tf.placeholder(tf.float32)